core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('auth_user.urls')),
    path('', include('reagents.urls')),
    path('', include('reports.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reagents/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('landingPage', LandingPage.as_view(), name='landing_page'),
    path('home/', HomeAdmin.as_view(), name='home_admin'),
    path('homeNormalUSer/', HomeNormalUser.as_view(), name='home_normal_user'),
    path('cadastrarReagente/', RegisterReagent.as_view(), name='register_reagent'),
    path('editarReagente/<str:id>', EditReagent.as_view(), name='edit_reagent'),
    path('estoque/liquidos/', ViewLiquids.as_view(), name='stock_liquids'),
    path('estoque/sólidos/', ViewSolids.as_view(), name='stock_solids'),
]

reagents/models.py
from django.db import models
import uuid

statesChoices = [
    ('L', 'Líquido'),
    ('S', 'Sólido')
]

controlChoices = [
    ('LI', 'Livre'),
    ('PF', 'Polícia Federal'),
]

# Create your models here
class Reagent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=144, unique=True)
    formula = models.CharField(max_length=144)
    limit = models.IntegerField()
    classification = models.CharField(max_length=64)
    incompatibility = models.ManyToManyField('self', blank=True)
    control = models.CharField(max_length=144, choices=controlChoices)
    state = models.CharField(max_length=64, choices=statesChoices)
    opening_date = models.DateField(null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        permissions = [
            ("can_add_reagent", "Cadastrar Reagente"),
            ("can_change_reagent", "Alterar Reagente"),
            ("can_delete_reagent", "Deletar Reagente"),
            ("can_view_reagent", "Ver Reagente"),
        ]

class ReagentBatch(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    amount = models.IntegerField()
    size = models.IntegerField()
    validity = models.DateField()
    fk_reagent = models.ForeignKey(Reagent, related_name='reagent_batch', null=False, on_delete=models.CASCADE)

    @property
    def formatted_validity(self):
        return self.validity.strftime('%d/%m/%Y')

    def __str__(self):
        val = self.validity.strftime('%d/%m/%Y')
        return "Lote de {} - {}".format(self.fk_reagent.name, val)

reagents/forms.py
from django import forms
from .models import *

class ReagentForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        label='NOME DO ITEM*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )   
    )

    formula = forms.CharField(
        required=True,
        label='FÓRMULA QUÍMICA*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )   
    )

    classification = forms.CharField(
        required=True,
        label='CLASSIFICAÇÃO QUÍMICA*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        ) 
    )

    state = forms.ChoiceField(
        required=True,
        label='CLASSIFIQUE O ITEM*',
        choices=[('Líquido/Sólido' , '')] + statesChoices,
        widget=forms.Select(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    amount = forms.IntegerField(
        required= False,
        label='QUANTIDADE',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    size = forms.IntegerField(
        required=False,
        label='TAMANHO DO FRASCO',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    limit = forms.IntegerField(
        required=True,
        label='LIMITE PARA AVISO*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    validity = forms.DateField(
        required=False,
        label='VALIDADE',
        widget=forms.DateInput(
            attrs={
                'type' : 'date',
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    control = forms.ChoiceField(
        label='CONTROLADO*',
        required=True,
        choices=controlChoices,
        widget=forms.Select(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    incompatibility = forms.ModelMultipleChoiceField(
        required=False,
        label='INCOMPATÍVEL COM',
        queryset=Reagent.objects.all(),
        widget= forms.SelectMultiple(attrs={'class':'form-control input-search js-example-basic-multiple'})
    )

    is_active = forms.BooleanField(
        required=False,
        label='É ativo?'
    )
    
    class Meta():
        model = Reagent
        fields = ['name', 'formula', 'classification', 'state', 'control', 'incompatibility', 'limit', 'is_active']

    def save(self, commit=True):
        instance = super().save(commit=False)
        
        # Salvar a instâcia
        if commit:
            instance.save()
        
        # Processar incompatibilidades
        incompatible_reagents = self.cleaned_data.get('incompatibility')
        if incompatible_reagents:
            for reagent in incompatible_reagents:
                reagent.incompatibility.add(instance)
                reagent.save()
        
        return instance

reagents/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from django.views import View

from .models import *
from .forms import *
from reports.models import *
from django.db.models import Q
from GeralUtilits import getErrors
from .utilits import *

from auth_user.decorators import *
from auth_user.forms import *


class LandingPage(View):
    @method_decorator(logged_out_required)
    def get(self, request):
        return render(request, 'landingPage.html')

def organize_reagents(queryset):
    formatted_queryset = []
    for reagent in queryset:
        reagent_batches = ReagentBatch.objects.filter(fk_reagent=reagent, amount__gt=0)  # Filtra batches com quantidade > 0
        formatted_queryset.append({
            'info': reagent,
            'batches': reagent_batches  # Associa os batches ao reagente
        })

    return agrupar_reagents_por_letra(ordenar_lista(formatted_queryset))

class HomeAdmin(View):
    @method_decorator(login_required)
    @method_decorator(superuser_required)
    def get(self, request):     
        liquids = Reagent.objects.filter(state='L')
        solids = Reagent.objects.filter(state='S')
            
        recentMovement = Movement.objects.filter().order_by('dt_movement')
        inventoryBalance = Reagent.objects.filter()

        context = {
            'solids' : organize_reagents(solids),
            'liquids' : organize_reagents(liquids),
            'recentMovement' : recentMovement,
            'inventoryBalance' : inventoryBalance,
        }
        
        return render(request, 'admin/homeAdmin.html', context)

class HomeNormalUser(View):
    @method_decorator(login_required)
    def get(self, request):
        liquids = Reagent.objects.filter(state='L')
        solids = Reagent.objects.filter(state='S')

        context = {
            'solids' : organize_reagents(solids),
            'liquids' : organize_reagents(liquids),
        }
        
        return render(request, 'reagents/homeUser.html', context)
        
class RegisterReagent(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_add_reagent', login_url='/'))
    def get(self, request):
        reagentForm = ReagentForm()

        context = {
            'form' : reagentForm
        }

        return render(request, 'reagents/register.html', context)
    
    def post(self, request):
        reagentForm = ReagentForm(request.POST)

        errors = getErrors([reagentForm])

        validity = request.POST.get('validity')
        amount = request.POST.get('amount')
        size = request.POST.get('size')

        if reagentForm.is_valid() and validity != None and amount != None and size != None:
            reagent = reagentForm.save()
            reagentBatch = ReagentBatch.objects.create(amount=amount, validity=validity, size=size, fk_reagent = reagent)
            reagentBatch.save()
            return redirect('/')
        else:
            context = {
                'form' : reagentForm,
                'errors' : errors
            }

            return render(request, 'reagents/register.html', context)

class EditReagent(View):
    def get(self, request, id):
        reagent = Reagent.objects.get(id=id)
        form = ReagentForm(instance=reagent)

        context = {
            'reagent' : reagent,
            'form' : form
        }

        return render(request, 'reagents/editReagent.html', context)

    def post(self, request, id):
        reagent = Reagent.objects.get(id=id)
        form = ReagentForm(request.POST, instance=reagent)
        errors = getErrors([form])

        if form.is_valid():
            form.save()

            return redirect('home_admin')

        context = {
            'errors' : errors,
            'reagent' : reagent,
            'form' : form
        }


        return render(request, 'reagents/editReagent.html', context)

class ViewLiquids(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_view_reagent', login_url='/'))
    def get(self, request):
        search = request.GET.get('search', "")

        passive_liquids = search_for_reagent(search, 'L')['passives']
        active_liquids = search_for_reagent(search, 'L')['actives']

        context = {
            'active_liquids' : organize_reagents(active_liquids),
            'passive_liquids' : organize_reagents(passive_liquids)
        }
        return render(request, 'reagents/liquids.html', context)
    
class ViewSolids(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_view_reagent', login_url='/'))
    def get(self, request):
        search = request.GET.get('search', "")

        passive_solids = search_for_reagent(search, 'S')['passives']
        active_solids = search_for_reagent(search, 'S')['actives']

        context = {
            'active_solids' : organize_reagents(active_solids),
            'passive_solids' : organize_reagents(passive_solids)
        }
        return render(request, 'reagents/solids.html', context)

templates/components/reagent/card_balance.html
{% load static %}

<style>
    .card_balance {
        display: flex;
        justify-content: space-between;
        padding: .4rem .8rem;
        margin-bottom: .8rem;
        box-shadow: 0px 4px 3px rgba(0, 0, 0, 0.20);
        border-radius: 10px;
        border: 1px solid #1e1e1e;
        align-items: center;
        font-weight: 500;
    }
    
    .card_balance .basic_info {
        display: flex;
        align-items: center;
    }

    .card_balance .basic_info img {
        margin-right: .4rem;
    }
</style>

<div class="card_balance">
    <div class="basic_info">
        <img src="{% static 'imgs/icons/balance.svg' %}" alt>
        {{batch.fk_reagent.name}}
    </div>

    <p class="validity">
        {{batch.validity}}
    </p>

    <img src="{% static 'imgs/icons/drop_down_button.svg' %}" alt>
</div>

templates/components/reagent/modal.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/reagents/modal.css' %}">

<div class="back none" id="reagent{{reagent.info.id}}">
    <article class="modal none">
        <div class="modal_header">
            <img src="{% static 'imgs/icons/info.svg' %}" alt="">
            <h2>Informações do Item</h2>
        </div>

        <div class="modal_body">
            <div class="body_item">
                <p class="title">Nome do Item</p>
                <p class="reagent_info">{{reagent.info.name}}</p>
            </div>

            <div class="body_item">
                <p class="title">Fórmula Química</p>
                <p class="reagent_info">{{reagent.info.formula}}</p>
            </div>

            <div class="body_item">
                <p class="title">Classificação Química</p>
                <p class="reagent_info">{{reagent.info.classification}}</p>
            </div>

            <div class="body_item">
                <p class="title">Tipo de Item</p>
                <p class="reagent_info">{{reagent.info.get_state_display}}</p>
            </div>

            <div class="body_item">
                <p class="title">Estado do Item</p>

                {% if reagent.info.is_active %}
                    <p class="reagent_info">Ativo</p>
                {% else %}
                    <p class="reagent_info">Passivo</p>
                {% endif %}
            </div>

            
            <!-- <div class="body_item">
                <p class="title">Tamanho do Frasco</p>
                <p class="reagent_info">{{reagent.size}}
                    {% if reagent.state == 'L' %}
                        ML
                    {% else %}
                        G
                    {% endif %}
                </p>
            </div> -->

            <!-- <div class="body_item">
                <p class="title">Estoque</p>
                <p class="reagent_info">{{reagent.amount}}</p>
            </div> -->

            <!-- <div class="body_item">
                <p class="title">Validade</p>
                <p class="reagent_info">{{reagent.formatted_validity}}</p>
            </div> -->

            <div class="body_item">
                <p class="title">Controlado</p>
                <p class="reagent_info">{{reagent.info.get_control_display}}</p>
            </div>
        </div>

        <div class="incompatibilities">
            <p class="title">Incompatibilidades</p>
            
            <div class="list">
                {% for inc in reagent.info.incompatibility.all %}
                    <p>
                        {{inc}}
                    </p>
                {% endfor %}
            </div>
        </div>

        <div class="batches">
            <p class="title">Variantes</p>

            <div class="batchesList">
                {% for batch in reagent.batches %}
                    <div class="batch_item">
                        <p>{{batch.amount}} unidades</p>
                        <p>Vence em: {{batch.formatted_validity}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="modal_btns">
            <button onclick="close_modal()" card_id="reagent{{reagent.info.id}}" class="close_modal btn_close">FECHAR ITEM</button>
            <a class="edit" href="{% url 'edit_reagent' id=reagent.info.id %}">
                <img src="{% static 'imgs/icons/edit.svg' %}" alt="">
                <p>EDITAR ITEM</p>
            </a>
        </div>
    </article>
</div>