core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('auth_user.urls')),
    path('', include('reagents.urls')),
    path('', include('reports.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from .managers import *
import uuid

# Listas
sectorCompleteChoices = [
    ('B' , 'Bolsista'),
    ('P', 'Professor'),
    ('A', 'Administração')
]

sectorChoices= [
    ('B' , 'Bolsista'),
    ('P', 'Professor'),
]

# Create your models here.

class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = None
    email = models.EmailField(unique = True, blank = False)
    name = models.CharField(max_length = 256)
    sector = models.CharField(max_length=64, choices=sectorCompleteChoices, default='A')
    approved = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        Group,
        related_name='user_groups',
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='user_permissions',
        blank=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    objects = UserManager()

    def __str__(self):
        return self.name
    
    @property
    def user_image(self):
        if " " in self.name:
           name = self.name.split(" ")
        else: name = self.name

        firstName = name[0]
        secondName = name[1]
        
        return firstName[0].upper() + secondName[0].upper()

reports/models.py
from django.db import models
import uuid

# Foreign keys models imports
from auth_user.models import *
from reagents.models import *

from datetime import date, datetime, timedelta
from django.utils import timezone

typeMovementChoices = [
    ('A', 'Adição'),
    ('R', 'Remoção'),
    ('T', 'Transferência')
]

# Create your models here.
class Movement(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    motivation = models.CharField(max_length=288)
    amount = models.IntegerField()
    movement_type = models.CharField(max_length=64, choices=typeMovementChoices)
    dt_movement = models.DateTimeField()
    validity = models.DateField(null=True)
    size = models.IntegerField(null=True)

    fk_reagent = models.ForeignKey(Reagent, related_name='reagent_movement', null=False, on_delete=models.CASCADE)
    fk_reagentBatch = models.ManyToManyField(ReagentBatch, related_name='batch_remove')
    fk_user = models.ForeignKey(User, related_name='responsible_movement', null=False,  on_delete=models.CASCADE)

    @property
    def formatted_dt_movement(self):
        return self.dt_movement.strftime('%d/%m/%Y')
    
    @property
    def formatted_dt_validity(self):
        if self.validity == None:
            return ''
        return self.validity.strftime('%d/%m/%Y')
    
    def __str__(self):
        year = str(self.dt_movement.year)
        month = str(self.dt_movement.month)
        day = str(self.dt_movement.day)
        return self.fk_reagent.name + ' ' + self.movement_type + ' '+ day + '/' + month + '/' + year
    
    class Meta:
        permissions = [
            ("can_add_movement", "Criar Movimentação")
        ]

class Request(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    approved = models.BooleanField(default=False)
    dt_request = models.DateTimeField()
    dt_response = models.DateTimeField(null=True, default=None, blank=True)
    size = models.IntegerField(null=True)

    fk_movement = models.ForeignKey(Movement, related_name='request_movement', null=False, on_delete=models.CASCADE)

    def __str__(self):
        year = str(self.dt_request.year)
        month = str(self.dt_request.month)
        day = str(self.dt_request.day)
        return self.fk_movement.fk_user.name + ' ' + day + '/' + month + '/' + year

class License(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt_register = models.DateField()
    dt_maturity = models.DateField(null=True)
    pdf = models.FileField(upload_to='pdfs/', unique=True)
    is_expired = models.BooleanField(default=False)

    @property
    def days_until_expiration(self):
        # Data de expiração é 365 dias após o registro
        expiration_date = self.dt_register + timedelta(days=365)
        today = timezone.now().date()
        days_left = (expiration_date - today).days

        
        # Garante que não retorne valores negativos
        return max(days_left, 0)
    
    def save(self, *args, **kwargs):
        if not self.dt_maturity:
            self.dt_maturity = self.dt_register + timedelta(days=365)
        
        super().save(*args, **kwargs)

templates/components/movements/card.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/movements/card.css' %}">

<div  class="movement_card {% if is_request %} card_request {% endif %} {% if is_removed %} is_removed {% endif %}">
    <div class="responsible">
        <div class="img_perfil">
            {{movement.fk_user.user_image}}
        </div>

        <div class="personal_info">
            <p class="name">{{movement.fk_user.name}}</p>
            <p class="sector">{{movement.fk_user.get_sector_display}}</p>
        </div>
    </div>

    <div class="movement_info">
        <div class="card_header">
            <h2>Item</h2>
        </div>

        <div class="card_body">
            <p class="name_reagent">{{movement.fk_reagent.name}}</p>
            <p>{{movement.fk_reagent.formula}}</p>
            <p>{{movement.fk_reagent.classification}}</p>
            <p>{{movement.get_movement_type_display}}</p>
            <p>{{movement.formatted_dt_movement}}</p>

            {% if is_request %}
                <button class="btn_show sty btn_show_move show_more" card_id="movement{{movement.id}}">Ver Mais</button>
            {% endif %}
        </div>

    </div>

    {% if is_request %}
        <div class="request_m_btns">
            <button class="approve actionButtons" url="{{request.urls.approve}}" data-id="{{ request.info.id }}">Aprovar</button>
            <button class="disapprove actionButtons" url="{{request.urls.desapprove}}" data-id="{{ request.info.id }}">Negar</button>
        </div>
    {% else %}
        <button class="btn_show btn_show_move {% if is_removed %} is_removed_button {% endif %}" card_id="movement{{movement.id}}">Ver Movimentação</button>
    {% endif %}
</div>

{% include 'components/movements/modal.html' %}

templates/components/movements/form_modal.html
{% load static %}
{% load reports_tags %}
{% get_movement_form as form %}

<link rel="stylesheet" href="{% static 'css/movements/modal_form.css' %}">

<div class="back none" id="movement_form">
    <form class="movements_form none" id="movements_form_id">
        {% csrf_token %}
        <div class="modal_header">
            <img src="{% static 'imgs/icons/movimentações.svg' %}" alt="">
            <h2>Movimentação de Item</h2>
        </div>

        <div class="modal_body">
            <div class="group_inputs">
                <div class="body_item">
                    {{form.fk_reagent.label_tag}}
                    {{form.fk_reagent}}
                </div>
                <div class="body_item">
                    {{form.movement_type.label_tag}}
                    {{form.movement_type}}
                </div>
                <div class="body_item">
                    {{form.amount.label_tag}}
                    {{form.amount}}
                </div>
            </div>



            <div class="body_item wide">
                {{form.motivation.label_tag}}
                {{form.motivation}}
            </div>

            <div class="body_item validity_field none">
                {{form.validity.label_tag}}
                {{form.validity}}
            </div>

            <div class="body_item size_field none">
                {{form.size.label_tag}}
                {{form.size}}
            </div>
        </div>

        <div class="modal_btns">
            <button onclick="close_movement_form_modal()" type="button" class="close_modal">FECHAR</button>
            
            <button class="save" type="submit">Salvar</button>
        </div>
    </form>
</div>

<script>
    document.getElementById('id_movement_type').addEventListener("change", function() {
        var validity_field = document.querySelector('.validity_field')
        var size_field = document.querySelector('.size_field')
        if (document.getElementById('id_movement_type').value == 'A') {
            validity_field.classList.remove('none')
            size_field.classList.remove('none')
        }
        else {
            validity_field.classList.add('none')
            size_field.classList.add('none')
        }
    })
    
    document.getElementById('movements_form_id').addEventListener('submit', function(event) {
        event.preventDefault(); // Evita o envio padrão do formulário

        const formData = new FormData(this); // Coleta os dados do formulário
        const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value; // Captura o token CSRF

        fetch('{% url "create_movement" %}', { // Substitua pelo endpoint correto da sua API
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': csrfToken // Inclui o token CSRF nos cabeçalhos
            }
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Erro na requisição: ' + response.statusText);
            }
            return response.json();
        })
        .then(data => {
            console.log('Success:', data);
            close_modal()
            alert(data.message)
        })
        .catch((error) => {
            console.error('Error:', error);
            // Aqui você pode tratar o erro
            // Ex: Mostrar mensagem de erro para o usuário
        });
    });
</script>

templates/components/movements/modal.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/movements/modal.css' %}">

<div class="back none" id="movement{{movement.id}}">
    <article class="modal movements">
        <div class="modal_header">
            <img src="{% static 'imgs/icons/movimentações.svg' %}" alt="">
            <h2>Informações da Movimentação</h2>
        </div>

        <div class="modal_body">
            <div class="body_item">
                <p class="title">Reagent</p>
                <p class="reagent_info">{{movement.fk_reagent.name}}</p>
            </div>

            <div class="body_item">
                <p class="title">Fórmula Química</p>
                <p class="reagent_info">{{movement.fk_reagent.formula}}</p>
            </div>

            <div class="body_item">
                <p class="title">Classificação Química</p>
                <p class="reagent_info">{{movement.fk_reagent.classification}}</p>
            </div>

            <div class="body_item wide">
                <p class="title">Motivação</p>
                <p class="reagent_info">{{movement.motivation}}</p>
            </div>

            <div class="body_item">
                <p class="title">Tipo de Movimentação</p>
                <p class="reagent_info">{{movement.get_movement_type_display}}</p>
            </div>

            {% if movement.movement_type == 'A' %}
                <div class="body_item">
                    <p class="title">Validade</p>
                    <p class="reagent_info">{{movement.formatted_dt_validity}}</p>
                </div>
            {% endif %}

            <div class="body_item">
                <p class="title">Responsável</p>
                <p class="reagent_info">{{movement.fk_user}}</p>
            </div>
        </div>

        <div class="modal_btns">
            <button onclick="close_modal()" card_id="movement{{movement.id}}" class="close_modal btn_close">FECHAR</button>
            </a>
        </div>
    </article>
</div>