core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('auth_user.urls')),
    path('', include('reagents.urls')),
    path('', include('reports.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reagents/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('landingPage', LandingPage.as_view(), name='landing_page'),
    path('home/', HomeAdmin.as_view(), name='home_admin'),
    path('homeNormalUSer/', HomeNormalUser.as_view(), name='home_normal_user'),
    path('cadastrarReagente/', RegisterReagent.as_view(), name='register_reagent'),
    path('editarReagente/<str:id>', EditReagent.as_view(), name='edit_reagent'),
    path('estoque/liquidos/', ViewLiquids.as_view(), name='stock_liquids'),
    path('estoque/sólidos/', ViewSolids.as_view(), name='stock_solids'),
]

reagents/models.py
from django.db import models
import uuid

statesChoices = [
    ('L', 'Líquido'),
    ('S', 'Sólido')
]

controlChoices = [
    ('LI', 'Livre'),
    ('PF', 'Polícia Federal'),
]

# Create your models here
class Reagent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=144, unique=True)
    formula = models.CharField(max_length=144)
    limit = models.IntegerField()
    classification = models.CharField(max_length=64)
    incompatibility = models.ManyToManyField('self', blank=True)
    control = models.CharField(max_length=144, choices=controlChoices)
    state = models.CharField(max_length=64, choices=statesChoices)
    opening_date = models.DateField(null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        permissions = [
            ("can_add_reagent", "Cadastrar Reagente"),
            ("can_change_reagent", "Alterar Reagente"),
            ("can_delete_reagent", "Deletar Reagente"),
            ("can_view_reagent", "Ver Reagente"),
        ]

class ReagentBatch(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    amount = models.IntegerField()
    size = models.IntegerField()
    validity = models.DateField()
    fk_reagent = models.ForeignKey(Reagent, related_name='reagent_batch', null=False, on_delete=models.CASCADE)

    @property
    def formatted_validity(self):
        return self.validity.strftime('%d/%m/%Y')

    def __str__(self):
        val = self.validity.strftime('%d/%m/%Y')
        return "Lote de {} - {}".format(self.fk_reagent.name, val)

reagents/forms.py
from django import forms
from .models import *

class ReagentForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        label='NOME DO ITEM*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )   
    )

    formula = forms.CharField(
        required=True,
        label='FÓRMULA QUÍMICA*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )   
    )

    classification = forms.CharField(
        required=True,
        label='CLASSIFICAÇÃO QUÍMICA*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        ) 
    )

    state = forms.ChoiceField(
        required=True,
        label='CLASSIFIQUE O ITEM*',
        choices=[('Líquido/Sólido' , '')] + statesChoices,
        widget=forms.Select(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    amount = forms.IntegerField(
        required= False,
        label='QUANTIDADE',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    size = forms.IntegerField(
        required=False,
        label='TAMANHO DO FRASCO',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    limit = forms.IntegerField(
        required=True,
        label='LIMITE PARA AVISO*',
        widget = forms.TextInput(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    validity = forms.DateField(
        required=False,
        label='VALIDADE',
        widget=forms.DateInput(
            attrs={
                'type' : 'date',
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    control = forms.ChoiceField(
        label='CONTROLADO*',
        required=True,
        choices=controlChoices,
        widget=forms.Select(
            attrs={
                'class' : 'shadow-lg text-sm rounded-full focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:focus:border-primary-500'
            }
        )
    )

    incompatibility = forms.ModelMultipleChoiceField(
        required=False,
        label='INCOMPATÍVEL COM',
        queryset=Reagent.objects.all(),
        widget= forms.SelectMultiple(attrs={'class':'form-control input-search js-example-basic-multiple'})
    )

    is_active = forms.BooleanField(
        required=False,
        label='É ativo?'
    )
    
    class Meta():
        model = Reagent
        fields = ['name', 'formula', 'classification', 'state', 'control', 'incompatibility', 'limit', 'is_active']

    def save(self, commit=True):
        instance = super().save(commit=False)
        
        # Salvar a instâcia
        if commit:
            instance.save()
        
        # Processar incompatibilidades
        incompatible_reagents = self.cleaned_data.get('incompatibility')
        if incompatible_reagents:
            for reagent in incompatible_reagents:
                reagent.incompatibility.add(instance)
                reagent.save()
        
        return instance

reagents/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from django.views import View

from .models import *
from .forms import *
from reports.models import *
from django.db.models import Q
from GeralUtilits import getErrors
from .utilits import *

from auth_user.decorators import *
from auth_user.forms import *


class LandingPage(View):
    @method_decorator(logged_out_required)
    def get(self, request):
        return render(request, 'landingPage.html')

def organize_reagents(queryset):
    formatted_queryset = []
    for reagent in queryset:
        reagent_batches = ReagentBatch.objects.filter(fk_reagent=reagent, amount__gt=0)  # Filtra batches com quantidade > 0
        formatted_queryset.append({
            'info': reagent,
            'batches': reagent_batches  # Associa os batches ao reagente
        })

    return agrupar_reagents_por_letra(ordenar_lista(formatted_queryset))

class HomeAdmin(View):
    @method_decorator(login_required)
    @method_decorator(superuser_required)
    def get(self, request):     
        liquids = Reagent.objects.filter(state='L')
        solids = Reagent.objects.filter(state='S')
            
        recentMovement = Movement.objects.filter().order_by('dt_movement')
        inventoryBalance = Reagent.objects.filter()

        context = {
            'solids' : organize_reagents(solids),
            'liquids' : organize_reagents(liquids),
            'recentMovement' : recentMovement,
            'inventoryBalance' : inventoryBalance,
        }
        
        return render(request, 'admin/homeAdmin.html', context)

class HomeNormalUser(View):
    @method_decorator(login_required)
    def get(self, request):
        liquids = Reagent.objects.filter(state='L')
        solids = Reagent.objects.filter(state='S')

        context = {
            'solids' : organize_reagents(solids),
            'liquids' : organize_reagents(liquids),
        }
        
        return render(request, 'reagents/homeUser.html', context)
        
class RegisterReagent(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_add_reagent', login_url='/'))
    def get(self, request):
        reagentForm = ReagentForm()

        context = {
            'form' : reagentForm
        }

        return render(request, 'reagents/register.html', context)
    
    def post(self, request):
        reagentForm = ReagentForm(request.POST)

        errors = getErrors([reagentForm])

        validity = request.POST.get('validity')
        amount = request.POST.get('amount')
        size = request.POST.get('size')

        if reagentForm.is_valid() and validity != None and amount != None and size != None:
            reagent = reagentForm.save()
            reagentBatch = ReagentBatch.objects.create(amount=amount, validity=validity, size=size, fk_reagent = reagent)
            reagentBatch.save()
            return redirect('/')
        else:
            context = {
                'form' : reagentForm,
                'errors' : errors
            }

            return render(request, 'reagents/register.html', context)

class EditReagent(View):
    def get(self, request, id):
        reagent = Reagent.objects.get(id=id)
        form = ReagentForm(instance=reagent)

        context = {
            'reagent' : reagent,
            'form' : form
        }

        return render(request, 'reagents/editReagent.html', context)

    def post(self, request, id):
        reagent = Reagent.objects.get(id=id)
        form = ReagentForm(request.POST, instance=reagent)
        errors = getErrors([form])

        if form.is_valid():
            form.save()

            return redirect('home_admin')

        context = {
            'errors' : errors,
            'reagent' : reagent,
            'form' : form
        }


        return render(request, 'reagents/editReagent.html', context)

class ViewLiquids(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_view_reagent', login_url='/'))
    def get(self, request):
        search = request.GET.get('search', "")

        passive_liquids = search_for_reagent(search, 'L')['passives']
        active_liquids = search_for_reagent(search, 'L')['actives']

        context = {
            'active_liquids' : organize_reagents(active_liquids),
            'passive_liquids' : organize_reagents(passive_liquids)
        }
        return render(request, 'reagents/liquids.html', context)
    
class ViewSolids(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('reagents.can_view_reagent', login_url='/'))
    def get(self, request):
        search = request.GET.get('search', "")

        passive_solids = search_for_reagent(search, 'S')['passives']
        active_solids = search_for_reagent(search, 'S')['actives']

        context = {
            'active_solids' : organize_reagents(active_solids),
            'passive_solids' : organize_reagents(passive_solids)
        }
        return render(request, 'reagents/solids.html', context)

templates/reagents/editReagent.html
{% extends 'components/base.html' %}
{% load static %}

{% block head %}

    <style>
        select{
            width: 100%;
        }
    </style>

    <script>
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>

    <style>
        #crud-modal {
            display: flex;
            width: 100%;
            justify-content: center;
        }

        #crud-modal form {
            display: flex;
            flex-direction: column;
            box-shadow: 1px 4px 4px rgba(0, 0, 0, 0.3);
            border-radius: 15px;
            padding: 2rem;
        }

        .form_header {
            display: flex;
            align-items: center;
            margin-bottom: 1.5rem ;
        }

        .form_header img {
            margin-right: .5rem;
            width: 40px;
        }

        .form_header h2 {
            font-weight: 400;
            font-size: 1.5rem;
        }

        #crud-modal form label {
            font-weight: 500;
            font-size: 14px;
        }

        #crud-modal form .field_div input, select, .select2 {
            border-radius: 5px !important;
            box-shadow: 0px 4px 3px rgba(0, 0, 0, 0.25);
            padding: .4rem .4rem;
            margin-bottom: 1.5rem;
            border: 1px solid #D9D9D9;
            width: 100% !important;
        }

        .select2 {
            padding: 0;
        }

        #id_is_active {
            width: 10px !important;
            margin-bottom: 1.5rem;
        }

        .group_inputs {
            display: flex;
            justify-content: space-between;
        }

        .group_inputs .field_div {
            display: flex;
            flex-direction: column;
            align-items: start;
            width: 22.5%;
        }

        .incompatibility {
            width: 100%;
        }

        #crud-modal .register_button {
            background-color: rgba(29, 138, 48, 1);
            color: white;
            padding: .7rem;
            border-radius: 15px;
            margin-top: 1rem;
            font-weight: 600;
        }

        @media screen and (min-width: 600px) and (max-width: 1024px) {
            .group_inputs {
                flex-direction: column;
                width: 100%;
            }

            .group_inputs .field_div {
                width: 100%;
            }
        }

        
        @media screen and (min-width: 200px) and (max-width: 600px) {
            .group_inputs {
                flex-direction: column;
                width: 100%;
            }

            .group_inputs .field_div {
                width: 100%;
            }
        }
    </style>
{% endblock %}

{% block content %}
    {% include 'components/navbar.html' %}

    <main>
        {% include 'components/errorModal.html' %}
        <section class="mainSection">
            {% include 'components/page_indication/presentation.html' with page="Editar item cadastrado" text="Nesta seção você poderá editar informações básicas do reagente" %}

            <div id="crud-modal" tabindex="-1">
                <form class="" method="post">
                    {% csrf_token %}
                    <div class="form_header">
                        <img src="{% static 'imgs/icons/add.svg' %}" alt="">
                        <h2>Editar Item</h2>
                    </div>

                    <div class="field_name field_div">
                        {{form.name.label_tag}}
                        {{form.name}}
                    </div>

                    <div class="group_inputs">
                        <div class="field_div">
                            {{form.formula.label_tag}}
                            {{form.formula}}
                        </div>
                        <div class="field_div">
                            {{form.classification.label_tag}}
                            {{form.classification}}
                        </div>
                        <div class="field_div">
                            {{form.state.label_tag}}
                            {{form.state}}
                        </div>
                    </div>

                    <div class="group_inputs">

                        <div class="field_div">
                            {{form.control.label_tag}}
                            {{form.control}}
                        </div>
                        <div class="field_div">
                            {{form.limit.label_tag}}
                            {{form.limit}}
                        </div>
                    </div>

                    <div class="">
                        {{form.is_active.label_tag}}
                        {{form.is_active}}
                    </div>

                    <div class="field_div incompatibility">
                        {{form.incompatibility.label_tag}}
                        {{form.incompatibility}}
                    </div>

                    <button type="submit" class="register_button">SALVAR</button>
                </form>
            </div>
        </section>

        {% include 'components/sidebar.html' %}
    </main>


{% endblock %}

{% block scripts %}

{% endblock %}

templates/reagents/homeUser.html
{% extends 'components/base.html' %}
{% load reports_tags %}
{% load static %}


{% block head %}
<link rel="stylesheet" href="{% static 'css/home_admin.css'%}">
<link rel="stylesheet" href="{% static 'css/output.css'%}">
{% endblock %}

{% block content %}
{% include 'components/navbar.html' %}

{% include 'components/movements/form_modal.html' %}

<main>
    <section>

        {% include 'components/page_indication/presentation.html' with page="Seu estoque" text="Nesta seção estarão listados itens do seu estoque sua visão geral, movimentações e muito mais." %}

        {% include 'components/page_indication/welcome.html' with text='Bem vindo,' username=user.name %}

        <!-- Essa parte vai ser a seleção da letra do composto requisitado, ainda não pega nenhuma informação -->
        <div class="alfabeto">
            <div class=" tab_alfa tag_inicio">
                <button class="inicio">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none"
                        stroke="#0A5517" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M19 12H6M12 5l-7 7 7 7" />
                    </svg>
                    Início
                </button>
            </div>
            <div class="letras">
                <button class="letra active"> A </button>
                <button class="letra"> B </button>
                <button class="letra"> C </button>
                <button class="letra"> D </button>
                <button class="letra"> E </button>
                <button class="letra"> F </button>
                <button class="letra"> G </button>
                <button class="letra"> H </button>
                <button class="letra"> I </button>
                <button class="letra"> J </button>
                <button class="letra"> K </button>
                <button class="letra"> L </button>
                <button class="letra"> M </button>
                <button class="letra"> N </button>
                <button class="letra"> O </button>
                <button class="letra"> P </button>
                <button class="letra"> Q </button>
                <button class="letra"> R </button>
                <button class="letra"> S </button>
                <button class="letra"> T </button>
                <button class="letra"> U </button>
                <button class="letra"> V </button>
                <button class="letra"> W </button>
                <button class="letra"> X </button>
                <button class="letra"> Y </button>
                <button class="letra"> Z </button>
            </div>
            <div class="tab_alfa tab_fim">
                <button class="fim">
                    Fim
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none"
                        stroke="#0A5517" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M5 12h13M12 5l7 7-7 7" />
                    </svg>
                </button>
            </div>
        </div>

        <!-- Separações entre visão geral, movimentação recente e Balanço de estoque -->
        <div class="container">
            <div class="tab-box">
                <div class="tabs secondary-tabs">
                    <button class="tab2-btn tab-liquids active" content-id="liquids"> Líquidos</button>
                    <button class="tab2-btn tab-solids" content-id="solids"> Sólidos</button>
                </div>
            </div>
            <div class="content-box">
                <div class="content active" id="geral">
                    <div class="liquids listReagents" id="liquids">
                        {% if liquids|length > 0 %}
                            {% for grupo in liquids %}
                            {% for letter, reagents in grupo.items %}
                            {% include 'components/group_reagents.html' %}
                            {% endfor %}
                            {% endfor %}
                        {% else %}
                            {% include 'components/no_results.html' with text="Nenhum reagente líquido cadastrado no momento" %}
                        {% endif %}
                    </div>

                    <div class="solids listReagents none" id="solids">
                        {% if solids|length > 0 %}
                            {% for grupo in solids %}
                            {% for letter, reagents in grupo.items %}
                            {% include 'components/group_reagents.html' %}
                            {% endfor %}
                            {% endfor %}
                        {% else %}
                            {% include 'components/no_results.html' with text="Nenhum reagente sólido cadastrado no momento" %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% include 'components/sidebar.html' %}
</main>
{% endblock %}

{% block scripts %}
<!-- Cração de movimento dentro da página -->
<script>
    document.getElementById('movementForm')?.addEventListener('submit', function (event) {
        event.preventDefault();
        const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        const formData = new FormData(this);

        fetch(this.action, {
            method: 'POST',
            headers: { 'X-CSRFToken': csrfToken },
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                if (data.message) {
                    alert(data.message);
                } else if (data.error) {
                    alert('Erro: ' + data.error);
                }
            });
    });
</script>

<!-- lógica para a troca de tabs PRINCIPAIS, ainda falta implementar as secundárias, que vão estar atreladas somente à tab "Visão Geral" 
Já é funcional, mas ainda não pega nenhuma informação real-->

<script>
    const tabs = document.querySelectorAll('.tab-btn');
    const all_content = document.querySelectorAll('.content');
    const secondaryTabs = document.querySelectorAll('.tab2-btn');

    tabs.forEach((tab, index) => {
        tab.addEventListener('click', (e) => {
            tabs.forEach(tab => tab.classList.remove('active'));
            tab.classList.add('active');

            all_content.forEach(content => content.classList.remove('active'));
            all_content[index].classList.add('active');

            // Verifica se a aba "Visão Geral" está ativa
            if (tab.getAttribute('content-id') === 'geral') {
                secondaryTabs.forEach(tab2 => tab2.classList.remove('disabled'));
            } else {
                secondaryTabs.forEach(tab2 => tab2.classList.add('disabled'));
            }
        });
    });
</script>

<!-- Lógica para a troca com o Alfabeto, ainda falta interligar com os elementos que vão aparecer na tela. -->
<script>
    const letras = document.querySelectorAll('.letra');
    const botaoInicio = document.querySelector('.inicio');
    const botaoFim = document.querySelector('.fim');

    function verificarLetrasAtivas() {
        const letraAtiva = document.querySelector('.letra.active');
        if (letraAtiva.textContent.trim() === 'A') {
            botaoInicio.disabled = true;
        } else {
            botaoInicio.disabled = false;
        }

        if (letraAtiva.textContent.trim() === 'Z') {
            botaoFim.disabled = true;
        } else {
            botaoFim.disabled = false;
        }
    }

    function selecionarLetra(index) {
        letras.forEach(letra => letra.classList.remove('active'));
        letras[index].classList.add('active');
        verificarLetrasAtivas();
    }

    letras.forEach((alfa, index) => {
        alfa.addEventListener('click', () => {
            selecionarLetra(index);
        });
    });

    botaoInicio.addEventListener('click', () => {
        selecionarLetra(0);
    });

    botaoFim.addEventListener('click', () => {
        selecionarLetra(letras.length - 1);
    });

    verificarLetrasAtivas();
</script>
<script src="{% static 'js/alter_reagent_types.js' %}"></script>
{% endblock %}

templates/reagents/register.html
{% extends 'components/base.html' %}
{% load static %}

{% block head %}
    <style>
        select{
            width: 100%;
        }
    </style>

    <script>
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>

    <style>
        #crud-modal {
            display: flex;
            width: 100%;
            justify-content: center;
        }

        #crud-modal form {
            display: flex;
            flex-direction: column;
            box-shadow: 1px 4px 4px rgba(0, 0, 0, 0.3);
            border-radius: 15px;
            padding: 2rem;
        }

        .form_header {
            display: flex;
            align-items: center;
            margin-bottom: 1.5rem ;
        }

        .form_header img {
            margin-right: .5rem;
            width: 40px;
        }

        .form_header h2 {
            font-weight: 400;
            font-size: 1.5rem;
        }

        #crud-modal form label {
            font-weight: 500;
            font-size: 14px;
        }

        #crud-modal form .field_div input, select, .select2 {
            border-radius: 5px !important;
            box-shadow: 0px 4px 3px rgba(0, 0, 0, 0.25);
            padding: .4rem .4rem;
            margin-bottom: 1.5rem;
            border: 1px solid #D9D9D9;
            width: 100% !important;
        }

        .select2 {
            padding: 0;
        }

        #id_is_active {
            width: 10px !important;
            margin-bottom: 1.5rem;
        }

        .group_inputs {
            display: flex;
            justify-content: space-between;
        }

        .group_inputs .field_div {
            display: flex;
            flex-direction: column;
            align-items: start;
            width: 22.5%;
        }

        .incompatibility {
            width: 100%;
        }

        #crud-modal .register_button {
            background-color: rgba(29, 138, 48, 1);
            color: white;
            padding: .7rem;
            border-radius: 15px;
            margin-top: 1rem;
            font-weight: 600;
        }

        @media screen and (min-width: 600px) and (max-width: 1024px) {
            .group_inputs {
                flex-direction: column;
                width: 100%;
            }

            .group_inputs .field_div {
                width: 100%;
            }
        }

        
        @media screen and (min-width: 200px) and (max-width: 600px) {
            .group_inputs {
                flex-direction: column;
                width: 100%;
            }

            .group_inputs .field_div {
                width: 100%;
            }
        }
    </style>
{% endblock %}

{% block content %}
    {% include 'components/navbar.html' %}

    <main>
        {% include 'components/errorModal.html' %}
        <section class="mainSection">
            {% include 'components/page_indication/presentation.html' with page="Cadastrar itens no seu estoque" text="Nesta seção você poderá adicionar facilmente itens no seu sistema." %}

            <div id="crud-modal" tabindex="-1">
                <form class="" method="post">
                    {% csrf_token %}
                    <div class="form_header">
                        <img src="{% static 'imgs/icons/add.svg' %}" alt="">
                        <h2>Cadastro de Item</h2>
                    </div>

                    <div class="field_name field_div">
                        {{form.name.label_tag}}
                        {{form.name}}
                    </div>

                    <div class="group_inputs">
                        <div class="field_div">
                            {{form.formula.label_tag}}
                            {{form.formula}}
                        </div>
                        <div class="field_div">
                            {{form.classification.label_tag}}
                            {{form.classification}}
                        </div>
                        <div class="field_div">
                            {{form.state.label_tag}}
                            {{form.state}}
                        </div>
                        <div class="field_div">
                            {{form.size.label_tag}}
                            {{form.size}}
                        </div>
                    </div>

                    <div class="group_inputs">
                        <div class="field_div">
                            {{form.amount.label_tag}}
                            {{form.amount}}
                        </div>
                        <div class="field_div">
                            {{form.validity.label_tag}}
                            {{form.validity}}
                        </div>
                        <div class="field_div">
                            {{form.control.label_tag}}
                            {{form.control}}
                        </div>
                        <div class="field_div">
                            {{form.limit.label_tag}}
                            {{form.limit}}
                        </div>
                    </div>

                    <div class="">
                        {{form.is_active.label_tag}}
                        {{form.is_active}}
                    </div>

                    <div class="field_div incompatibility">
                        {{form.incompatibility.label_tag}}
                        {{form.incompatibility}}
                    </div>

                    <button type="submit" class="register_button"> CADASTRAR ITEM </button>
                </form>
            </div>
        </section>

        {% include 'components/sidebar.html' %}
    </main>


{% endblock %}

{% block scripts %}

{% endblock %}

templates/reagents/registerMovement.html
{% extends 'components/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
{% endblock %}

{% block scripts %}
{% endblock %}